<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>knee_sensor_interface</name>
  <version>0.0.0</version>
  <description>ROS 2 interface to read a PIC HS-3511-02-0300 latching Hall on GPIO (libgpiod v2 edge detection)</description>
  <maintainer email="jdurst2000@gmail.com">jdurs</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>builtin_interfaces</depend>
  <build_depend>libgpiod-dev</build_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>odrive_interface</exec_depend>
  <exec_depend>encoder_interface</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
